// Generated by https://quicktype.io

export type LoginResponse = {
    login: { [key: string]: string };
};

// Generated by https://quicktype.io

export type ErrorResponse = {
    errors: ErrorElement[];
    data: null;
};

export type ErrorElement = {
    message: string;
    locations: Location[];
    path: string[];
    extensions: Extensions;
};

export type Extensions = {
    code: string;
    exception: Exception;
};

export type Exception = {
    code: number;
    data: ErrData;
    stacktrace: string[];
};

export type ErrData = {
    statusCode: number;
    error: string;
    message: Datum[];
    data: Datum[];
};

export type Datum = {
    messages: Message[];
};

export type Message = {
    id: string;
    message: string;
};

export type Location = {
    line: number;
    column: number;
};
